# Generated by Django 4.2.3 on 2023-07-14 08:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='product_name'),
        ),
    ]
