# Generated by Django 4.2.3 on 2023-07-14 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, help_text='www.example.com', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
