# Generated by Django 4.2.3 on 2023-07-14 16:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_address_rename_organization_name_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployee',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='role'),
        ),
    ]
