# Generated by Django 4.2.3 on 2023-07-15 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_alter_organizationemployee_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationemployee',
            name='user',
            field=models.ManyToManyField(help_text='It is employee of the comapny.', related_name='organization_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
